language: node_js
node_js:
  - "0.12.4"
before_install:
  - npm install -g grunt
  - npm install -g grunt-cli
  - npm install docco
  - npm install uglify-js
script:
  - npm run build
  - npm run test
  - npm run doc
after_success:
  - npm run coveralls
notifications:
  email: true
sudo: false